#!/bin/bash
status=`acpi -b | awk '{print $3}' | tr -d , | head -n 1`
percent=`acpi -b | awk '{print $4}' | cut -d % -f 1 | head -n 1`
if [[ $percent -lt 20 ]]
then 
	echo " ";
elif [[ $percent -lt 40 ]]
then 
	echo " "
elif [[ $percent -lt 60 ]]
then
	echo " ";
elif [[ $percent -lt 80 ]]
then
	echo " ";
else
	echo " ";
fi
