#!/bin/bash

LOC=$(curl -s ipinfo.io | jq '.loc' | sed -e 's/^"//'  -e 's/"$//')
URL="https://api.forecast.io/forecast/$(cat $HOME/.dotfiles/conky/forecast_api_key)/$LOC"

DATA=$(curl -s $URL | jq '.currently')

TEMP=$(echo $DATA | jq '.temperature')
SUM=$(echo $DATA | jq '.summary' | sed -e 's/^"//'  -e 's/"$//')
ICON_STR=$(echo $DATA | jq '.icon')
ICON=$(cat /home/elliott/.dotfiles/conky/icons.json | jq ".[$ICON_STR]" | sed -e 's/^"//'  -e 's/"$//')

echo $ICON > /home/elliott/.tmp/weather/icon
echo $SUM $TEMP > /home/elliott/.tmp/weather/current
