#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export PATH="$PATH:$HOME/.dotfiles/X:$HOME/.bin:$HOME/bin"

xrdb -merge ~/.dotfiles/X/xresources

[ -e ~/.screen_setup ] && source ~/.screen_setup

[ -e ~/.fehbg ] && source ~/.fehbg

[ -e ~/.dunstrc ] && dunst -config ~/.dunstrc & 

udiskie &

xautolock -time 7 -locker lock &

[ -e ~/.config/yabar/yabar.conf ] && yabar &

[ -e ~/.compton.conf ] && compton --config ~/.compton.conf &

>> /dev/null which nm-applet && nm-applet &
>> /dev/null which blueman-applet && blueman-applet &

i3

true
