#!/bin/bash

# one liner for data
# DATA=curl "https://api.forecast.io/forecast/$(cat ~/.dotfiles/scripts/forecast_api_key)/$(curl ipinfo.io | jq '.loc' | sed -e 's/^"//g' -e 's/"$//g')" | jq '.currently'

LOC=$(curl -s ipinfo.io | jq '.loc' | sed -e 's/^"//'  -e 's/"$//')

if [ -e ~/.dotfiles/scripts/forecast_api_key ]; then 
  URL="https://api.forecast.io/forecast/$(cat ~/.dotfiles/scripts/forecast_api_key)/$LOC"
else
  echo "Be sure to set up your api key at api.forecast.io"
  echo "  Put the key in $HOME/.dotfiles/scripts/forecast_api_key"
  exit 1
fi

DATA=$(curl -s $URL | jq '.currently')

TEMP=$(echo $DATA | jq '.apparentTemperature')
SUM=$(echo $DATA | jq '.summary' | sed -e 's/^"//'  -e 's/"$//')
ICON_STR=$(echo $DATA | jq '.icon')
ICON=$(cat ~/.dotfiles/scripts/icons.json | jq ".[$ICON_STR]" | sed -e 's/^"//'  -e 's/"$//')

echo $ICON > $HOME/.tmp/weather/icon
echo $SUM $TEMP > $HOME/.tmp/weather/current
